# Generated by Django 4.2.29 on 2026-03-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Network', max_length=120)),
                ('dataset', models.CharField(default='xor', max_length=40)),
                ('layer_sizes', models.TextField()),
                ('activations', models.TextField()),
                ('loss_function', models.CharField(default='mse', max_length=40)),
                ('learning_rate', models.FloatField(default=0.01)),
                ('epochs', models.IntegerField(default=1000)),
                ('weights', models.TextField(blank=True)),
                ('history_loss', models.TextField(blank=True)),
                ('history_acc', models.TextField(blank=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='nn_app.trainingsession')),
            ],
        ),
    ]
